### ISSUE TITLE
Setting up SeoSnap without Docker

### ISSUE THREAD

**Issue by d6michalszorad** [experius/SeoSnap#5]
We would like to run SeoSnap, but we can not install Docker on the production machines. Are there any ways of running SeoSnap without Docker? If yes, what are the options?

**Comment by egordm** [comment]
Hi @d6michalszorad,

The other option is setting up each component individually. 
To do this you need python 3.7 installed, a rendertron instance and a mysql database.
Then you need to create the .env file in each repo and change the default files to ones corresponding to your local config (database host and login, rendertron endpoint etc.). 
Then since there is not yet a definitive guide on dockerless setup, I would suggest you follow the steps defined in docker file. Mainly the last step (running of the program.)

Hope this helps you a bit.

**Comment by lewisvoncken** [comment]
@d6michalszorad 

due to inactivity I will close the issue
